version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    networks:
      - airflow_airflow_default
    volumes:
      - ./datalake:/opt/spark/datalake
    ports:
      - "7077:7077"
      - "8888:8080"

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./datalake:/opt/airflow/datalake
    networks:
      - airflow_airflow_default

  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - airflow_airflow_default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=default

networks:
  airflow_airflow_default:
    external: true

volumes:
  clickhouse_data: